name: Test

on:
  pull_request:
  push:
    branches: [main]

env:
  BACKEND_DIR: backend

jobs:
  tests:
    name: Run unit-tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.BACKEND_DIR }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "${{ env.BACKEND_DIR }}/pyproject.toml"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake pkg-config

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.7.19"

      - name: Install the project
        run: uv sync --extra dev

      - name: Install recommendation-core
        run: uv pip install -e ../recommendation-core

      - name: Run tests
        # Run tests with recommendation-core available
        run: PYTHONPATH=src uv run -m pytest tests -v
