name: Test

on:
  pull_request:
  push:
    branches: [main]

env:
  BACKEND_DIR: backend

jobs:
  tests:
    name: Verify environment setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.BACKEND_DIR }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "${{ env.BACKEND_DIR }}/pyproject.toml"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake pkg-config

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.19"

      - name: Install the project
        run: uv sync --extra dev

      - name: Try to install recommendation-core (optional)
        run: |
          echo "Attempting to install recommendation-core..."
          if uv pip install -e ../recommendation-core; then
            echo "✅ recommendation-core installed successfully"
          else
            echo "⚠️ recommendation-core installation failed, but environment is ready"
          fi

      - name: Verify environment
        run: |
          echo "✅ Environment setup complete"
          echo "Python version: $(python --version)"
          echo "uv version: $(uv --version)"
          echo "Installed packages:"
          uv pip list
